# Generated by Django 4.0.2 on 2022-02-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_by',
        ),
    ]
