# Generated by Django 4.0.2 on 2022-02-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_remove_game_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameimages',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameimages',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='gamerating',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamerating',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='gamereviews',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gamereviews',
            old_name='player_id',
            new_name='player',
        ),
    ]
