# Generated by Django 4.0.2 on 2022-02-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0003_rename_category_id_gamecategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raterprojectapi.player'),
            preserve_default=False,
        ),
    ]
